version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketduck-app
    ports:
      - "8987:8987"
    depends_on:
      - db
      - redis
      - redis-dev
    networks:
      - app-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:8.0.32
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "13307:3306"
    env_file:
      - .env
    volumes:
      - /home/sussa/temp/MYSQL:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "16379:6379"
    networks:
      - app-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-dev:
    image: redis:latest
    command: redis-server --port 6378
    container_name: redis_boot_dev
    hostname: redis_boot_dev
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "16378:6378"
    networks:
      - app-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network: