server:
  port: 8987
  servlet:
    context-path: /
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  tomcat:
    max-threads: 200
    max-connections: 10000
    connection-timeout: 5000
    max-http-form-post-size: 52428800 # 50MB in bytes
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false

spring:
  datasource:
    url: ${MAIN_DEV_DB_URL}
    username: ${MAIN_DEV_DB_ID}
    password: ${MAIN_DEV_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 24
      connection-timeout: 30000
      validation-timeout: 2000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: never
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: ${REDIS_DEV_PORT}

logging:
  level:
    root: INFO
    com.devgang.marketduck: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/marketduck-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{requestId} %X{clientIp} %X{username} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{requestId} %X{clientIp} %X{username} %-5level %logger{36} - %msg%n"

mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    auth: true
    starttls:
      enable: true
  subject:
    user:
      registration: Thank you for joining our service!
      verification: Please complete verification. Thank you!
  template:
    name:
      user:
        join: email-registration-member

cloud:
  aws:
    s3:
      bucket: marketduck-dev
      dir: /marketduck
    region:
      static: ap-northeast-2
    stack:
      auto: false

springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
    enabled: ${SWAGGER_ENABLED:true}
  api-docs:
    path: /api-docs
    enabled: ${SWAGGER_ENABLED:true}
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
    - /open-api/**
  show-login-endpoint: false

oauth:
  naver:
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
    secret: ${NAVER_SECRET_KEY}
